/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBPJS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class LayananPembayaran extends javax.swing.JFrame {

    /**
     * Creates new form LayananPendaftaran
     */
    public LayananPembayaran() {
        initComponents();
    }
public void clear(){
    txt_bpjs.setText("");
    txt_nama.setText("");
    txt_biaya.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_bpjs = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_biaya = new javax.swing.JTextField();
        kls1 = new javax.swing.JRadioButton();
        kls2 = new javax.swing.JRadioButton();
        kls3 = new javax.swing.JRadioButton();
        CARI = new javax.swing.JButton();
        SIMPAN = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        KEMBALI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU LAYANAN PEMBAYARAN BPJS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("NOMOR BPJS                    :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("NAMA                                  :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("BIAYA                                  :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("TINGKAT FASKES           :");

        txt_bpjs.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        txt_nama.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        txt_biaya.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        kls1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(kls1);
        kls1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        kls1.setText("KLS1");
        kls1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kls1MouseClicked(evt);
            }
        });

        kls2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(kls2);
        kls2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        kls2.setText("KLS2");
        kls2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kls2MouseClicked(evt);
            }
        });

        kls3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(kls3);
        kls3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        kls3.setText("KLS3");
        kls3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kls3MouseClicked(evt);
            }
        });

        CARI.setBackground(new java.awt.Color(255, 255, 255));
        CARI.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        CARI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/TEMUKAN.png"))); // NOI18N
        CARI.setText("CARI");
        CARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARIActionPerformed(evt);
            }
        });

        SIMPAN.setBackground(new java.awt.Color(255, 255, 255));
        SIMPAN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/simpan.png"))); // NOI18N
        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        EDIT.setBackground(new java.awt.Color(255, 255, 255));
        EDIT.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        EDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/edit.png"))); // NOI18N
        EDIT.setText("EDIT");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        HAPUS.setBackground(new java.awt.Color(255, 255, 255));
        HAPUS.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        HAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/HAPUS.png"))); // NOI18N
        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        KEMBALI.setBackground(new java.awt.Color(255, 255, 255));
        KEMBALI.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        KEMBALI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/BACK.png"))); // NOI18N
        KEMBALI.setText("KEMBALI");
        KEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KEMBALIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(txt_bpjs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CARI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(kls1)
                                        .addGap(36, 36, 36)
                                        .addComponent(kls2)
                                        .addGap(18, 18, 18)
                                        .addComponent(kls3)))))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SIMPAN)
                .addGap(18, 18, 18)
                .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HAPUS)
                .addGap(18, 18, 18)
                .addComponent(KEMBALI)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_bpjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CARI))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kls1)
                    .addComponent(kls2)
                    .addComponent(kls3))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KEMBALI)
                    .addComponent(HAPUS)
                    .addComponent(EDIT)
                    .addComponent(SIMPAN))
                .addGap(0, 115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1061, 835));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KEMBALIActionPerformed
        MenuLayanan mn = new MenuLayanan();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KEMBALIActionPerformed

    private void CARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARIActionPerformed
        Data_Pembayaran db = new Data_Pembayaran();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CARIActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        String bpjs = txt_bpjs.getText();
        String nama = txt_nama.getText();
        String faskes = null;
        if (kls1.isSelected()){
        faskes = "KLS1";
        }
        else if(kls2.isSelected()){
        faskes = "KLS2";
        }else if (kls3.isSelected()){
            faskes = "KLS3";
        }
        String biaya = txt_biaya.getText();
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "INSERT INTO pembayaran VALUES (?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, bpjs);
            p.setString(2, nama);
            p.setString(3, faskes);
            p.setString(4, biaya);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(rootPane, "BERHASIL DISIMPAN");
         String vbuttonGroup1 = null;
         buttonGroup1.getSelection();
         
        } catch (Exception e) {
            System.out.println("Data yang disimpan error"+e);
        }
        clear();
    }//GEN-LAST:event_SIMPANActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        String bpjs = txt_bpjs.getText();
        String nama = txt_nama.getText();
       String faskes;
        if (kls1.isSelected()){
        faskes = "KLS1";
        }
        else if(kls2.isSelected()){
        faskes = "KLS2";
        }else{
            faskes = "KLS3";
        }
        String biaya = txt_biaya.getText();
        try{
           Connection c=koneksi.getKoneksi();
           String sql="UPDATE pembayaran SET nama=?,faskes=?,biaya=? WHERE nobpjs=?";
           PreparedStatement p=c.prepareStatement(sql);
           p.setString(4, bpjs);
           p.setString(3, biaya);
           p.setString(2, faskes);
           p.setString(1, nama);
           p.executeUpdate();
           p.close();

         String vbuttonGroup1 = null;
         buttonGroup1.getSelection();
           JOptionPane.showMessageDialog(rootPane, "berhasil di update");
       }catch(Exception e){
           System.out.println("tidak berhasil di update"+e.getMessage());
       }
        clear();
    }//GEN-LAST:event_EDITActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        String bpjs = txt_bpjs.getText();
        String nama = txt_nama.getText();
        String faskes;
        if (kls1.isSelected()){
        faskes = "KLS1";
        }
        else if(kls2.isSelected()){
        faskes = "KLS2";
        }else if (kls3.isSelected()){
            faskes = "KLS3";
        }
        String biaya = txt_biaya.getText();
        try{
           Connection c=koneksi.getKoneksi();
           String sql="DELETE FROM pembayaran WHERE nobpjs=?";
           PreparedStatement p=c.prepareStatement(sql);
           p.setString(1, bpjs);
           p.executeUpdate();
           p.close();
           JOptionPane.showMessageDialog(rootPane, "berhasil di hapus");
       }catch(Exception e){
           System.out.println("tidak berhasil di hapus"+e.getMessage());
       }
        clear();
    }//GEN-LAST:event_HAPUSActionPerformed

    private void kls3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kls3MouseClicked
        JOptionPane.showMessageDialog(rootPane, "Biaya Faskes Kelas 3/bulan ialah \nRp.35.000");
        txt_biaya.setText("35000");
    }//GEN-LAST:event_kls3MouseClicked

    private void kls2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kls2MouseClicked
        JOptionPane.showMessageDialog(rootPane, "Biaya Faskes Kelas 2/bulan ialah \nRp.100.000");
        txt_biaya.setText("100000");
    }//GEN-LAST:event_kls2MouseClicked

    private void kls1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kls1MouseClicked
        JOptionPane.showMessageDialog(rootPane, "Biaya Faskes Kelas 1/bulan ialah \nRp.150.000");
        txt_biaya.setText("150000");
    }//GEN-LAST:event_kls1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayananPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayananPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayananPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayananPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayananPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CARI;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton KEMBALI;
    private javax.swing.JButton SIMPAN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton kls1;
    public static javax.swing.JRadioButton kls2;
    public static javax.swing.JRadioButton kls3;
    public static javax.swing.JTextField txt_biaya;
    public static javax.swing.JTextField txt_bpjs;
    public static javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
