/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBPJS;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javafx.scene.control.RadioButton;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class LayananPendaftaran extends javax.swing.JFrame {

    /**
     * Creates new form LayananPendaftaran
     */
    public LayananPendaftaran() {
        initComponents();
    }
public void clear(){
       nik_txt.setText("");
       nama_txt.setText("");
       alamat_txt.setText("");
   } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nik_txt = new javax.swing.JTextField();
        nama_txt = new javax.swing.JTextField();
        alamat_txt = new javax.swing.JTextField();
        kls1_rb = new javax.swing.JRadioButton();
        kls2_rb = new javax.swing.JRadioButton();
        kls3_rb = new javax.swing.JRadioButton();
        CARI = new javax.swing.JButton();
        SIMPAN = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        KEMBALI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU LAYANAN PENDAFTARAN BPJS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("NIK                                      :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("NAMA                                  :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("ALAMAT                             :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("TINGKAT FASKES           :");

        nik_txt.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        nama_txt.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        alamat_txt.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        kls1_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(kls1_rb);
        kls1_rb.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        kls1_rb.setText("KLS1");

        kls2_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(kls2_rb);
        kls2_rb.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        kls2_rb.setText("KLS2");

        kls3_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(kls3_rb);
        kls3_rb.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        kls3_rb.setText("KLS3");

        CARI.setBackground(new java.awt.Color(255, 255, 255));
        CARI.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        CARI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/TEMUKAN.png"))); // NOI18N
        CARI.setText("CARI");
        CARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARIActionPerformed(evt);
            }
        });

        SIMPAN.setBackground(new java.awt.Color(255, 255, 255));
        SIMPAN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/simpan.png"))); // NOI18N
        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        EDIT.setBackground(new java.awt.Color(255, 255, 255));
        EDIT.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        EDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/edit.png"))); // NOI18N
        EDIT.setText("EDIT");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        HAPUS.setBackground(new java.awt.Color(255, 255, 255));
        HAPUS.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        HAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/HAPUS.png"))); // NOI18N
        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        KEMBALI.setBackground(new java.awt.Color(255, 255, 255));
        KEMBALI.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        KEMBALI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBPJS/BACK.png"))); // NOI18N
        KEMBALI.setText("KEMBALI");
        KEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KEMBALIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(kls1_rb)
                        .addGap(18, 18, 18)
                        .addComponent(kls2_rb)
                        .addGap(18, 18, 18)
                        .addComponent(kls3_rb))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alamat_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(37, 37, 37)
                            .addComponent(nik_txt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CARI))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(30, 30, 30)
                            .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(SIMPAN)
                .addGap(18, 18, 18)
                .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(HAPUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KEMBALI)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nik_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CARI))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kls1_rb)
                        .addComponent(kls2_rb)
                        .addComponent(kls3_rb)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KEMBALI)
                    .addComponent(HAPUS)
                    .addComponent(EDIT)
                    .addComponent(SIMPAN))
                .addGap(0, 69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1055, 827));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KEMBALIActionPerformed
        MenuLayanan mn = new MenuLayanan();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KEMBALIActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        String nik = nik_txt.getText();
        String nama = nama_txt.getText();
        String alamat = alamat_txt.getText();
        String faskes;
        if (kls1_rb.isSelected()){
        faskes = "KLS1";
        }
        else if(kls2_rb.isSelected()){
        faskes = "KLS2";
        }else{
            faskes = "KLS3";
        }
        
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "INSERT INTO pendaftaran VALUES (?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nik);
            p.setString(2, nama);
            p.setString(3, alamat);
            p.setString(4, faskes);

            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(rootPane, "BERHASIL DISIMPAN");
         String vbuttonGroup1 = null;
         buttonGroup1.getSelection();
        } catch (Exception e) {
            System.out.println("Data yang disimpan error"+e);
        }
        clear();
    }//GEN-LAST:event_SIMPANActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        String nik = nik_txt.getText();
        String nama = nama_txt.getText();
        String alamat = alamat_txt.getText();
        String faskes;
        if (kls1_rb.isSelected()){
        faskes = "KLS1";
        }
        else if(kls2_rb.isSelected()){
        faskes = "KLS2";
        }else{
            faskes = "KLS3";
        }
        try{
           Connection c=koneksi.getKoneksi();
           String sql="UPDATE pendaftaran SET nama=?,alamat=?,faskes=? WHERE nik=?";
           PreparedStatement p=c.prepareStatement(sql);
           p.setString(4, nik);
           p.setString(3, faskes);
           p.setString(2, alamat);
           p.setString(1, nama);
           p.executeUpdate();
           p.close();

         String vbuttonGroup1 = null;
         buttonGroup1.getSelection();
           JOptionPane.showMessageDialog(rootPane, "berhasil di update");
       }catch(Exception e){
           System.out.println("tidak berhasil di update"+e.getMessage());
       }
        clear();
    }//GEN-LAST:event_EDITActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        String kode = nik_txt.getText();
        try{
           Connection c=koneksi.getKoneksi();
           String sql="DELETE FROM pendaftaran WHERE nik=?";
           PreparedStatement p=c.prepareStatement(sql);
           p.setString(1, kode);
           p.executeUpdate();
           p.close();
         String vbuttonGroup2 = null;
         buttonGroup1.getSelection();
           JOptionPane.showMessageDialog(rootPane, "berhasil di hapus");
       }catch(Exception e){
           System.out.println("tidak berhasil di hapus"+e.getMessage());
       }
        clear();
    }//GEN-LAST:event_HAPUSActionPerformed

    private void CARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARIActionPerformed
        Data_Peendaftaran df = new Data_Peendaftaran();
        df.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CARIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayananPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayananPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayananPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayananPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayananPendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CARI;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton KEMBALI;
    private javax.swing.JButton SIMPAN;
    public static javax.swing.JTextField alamat_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton kls1_rb;
    public static javax.swing.JRadioButton kls2_rb;
    public static javax.swing.JRadioButton kls3_rb;
    public static javax.swing.JTextField nama_txt;
    public static javax.swing.JTextField nik_txt;
    // End of variables declaration//GEN-END:variables
}
